spring:
  datasource:
    url: jdbc:h2:file:./data/weathering-db  # 현재 폴더 기준으로 DB 파일 생성
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true